# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
description: Installs the Fastly CLI

# Define a job to be invoked later in a workflow.
#          TAG=0.1.$CIRCLE_BUILD_NUM
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  docker: circleci/docker@1.7.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: lotusbaba/fastly-images
    steps:
      - docker/build:
          tag: latest 
          dockerfile: Dockerfile 
          image: fastly-cae-build
    parallelism: 1
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    
    docker:
#      - image: lotusbaba/fastly-images:0.1.$CIRCLE_BUILD_NUM
      - image: lotusbaba/fastly-images:latest
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps    
    description: Call compute serve and run commands.
    working_directory: ~/.branch-dir/First-Project
    steps:
      - checkout
      - run:
          name: "Call compute serve test 1"
          command: |
             TAG=latest
             docker run -d -p 7676:7676 --name fastly-cae-server --entrypoint ~/.bin/fastly lotusbaba/fastly-images:latest compute serve]
             docker exec fastly-cae-server curl --retry 10 --retry-connrefused http://localhost:7676
    parallelism: 1
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows

workflows:
  say-hello-workflow:
    jobs:
      - example-job
      - say-hello